name: Deploy to Lambda
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Building function code
        run: | 
          cd lambda
          npm ci
          npm run build --if-present
      - name: ZIP function code
        run: |
          zip -r ../function.zip *
        working-directory: lambda/
      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code --function-name THESIS-secureinbrowser --zip-file fileb://function.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-north-1