name: deploy to lambda
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  # in the lambda folder
  push:
    branches:
      - main
    paths:
      - 'lambda/**'
jobs:

  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
        working-directory: lambda
      - name: Deploy to Lambda
        run: aws lambda update-function-code --function-name THESIS-secureinbrowser --zip-file fileb://lambda.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-north-1
      - name: Cleanup
        run: rm lambda.zip
